project:
  type: website

website:
  title: "Kelley Atwood"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Assignments.qmd
        text: Assignments

format:
  html:
    theme: jekyll-theme-architect
    css: styles.css
    toc: true

editor: visual

